### ISSUE TITLE
What's this? How I use it?

### ISSUE THREAD

**Issue by cinvro** [fishery/legacy#1]
Could anyone explain what exactly this plugin does? I installed it, nothing changes.

**Comment by bucaran** [comment]
I am sorry for the lack of documentation.

The plugin install the following dependencies:

* autoinit
* git-branch-name
* git-is-repo
* git-is-dirty
* git-is-staged
* git-is-stashed
* git-is-touched

Some of which are needed to run Oh My Fish! plugins. 

A few examples:

If you are using the plugin:

* https://github.com/oh-my-fish/plugin-tab

You don't need this plugin, as Fisherman can run tab OK.

But if you are using the plugin:
* https://github.com/oh-my-fish/plugin-fasd

You will need `autoinit` which is included in this bunch.

Depending on how Oh My Fish! continues to evolve this plugin may include more or less deps. In fact, this plugin may completely dissapear if Oh My Fish! and Fisherman become more compatible.

**Comment by bucaran** [comment]
If you have other questions just let me know. Closing as resolved.
